"""empty message

Revision ID: 96f4ca6bc709
Revises: e8333e23cd8b
Create Date: 2020-01-19 00:19:10.084011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f4ca6bc709'
down_revision = 'e8333e23cd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('folder', sa.String(length=4096), nullable=True))
    op.drop_index('ix_channel_url', table_name='channel')
    op.create_unique_constraint(None, 'channel', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='unique')
    op.create_index('ix_channel_url', 'channel', ['url'], unique=1)
    op.drop_column('channel', 'folder')
    # ### end Alembic commands ###
