"""empty message

Revision ID: e8333e23cd8b
Revises: 
Create Date: 2020-01-18 15:28:07.333527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8333e23cd8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('ydl_options', sa.String(length=128), nullable=True),
    sa.Column('monitor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_name'), 'channel', ['name'], unique=True)
    op.create_index(op.f('ix_channel_url'), 'channel', ['url'], unique=True)
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(length=11), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_published_date'), 'video', ['published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_published_date'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_channel_url'), table_name='channel')
    op.drop_index(op.f('ix_channel_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
